(()=>{var l=(t,e,r)=>new Promise((n,c)=>{var s=a=>{try{o(r.next(a))}catch(i){c(i)}},p=a=>{try{o(r.throw(a))}catch(i){c(i)}},o=a=>a.done?n(a.value):Promise.resolve(a.value).then(s,p);o((r=r.apply(t,e)).next())});var u;document.addEventListener("DOMContentLoaded",()=>{let t=document.querySelector(".w-richtext"),e=t.innerHTML,r=new RegExp("\\{\\{(.*?)\\}\\}","gs"),n=e.match(r);n&&n.forEach(c=>l(void 0,null,function*(){if(c.includes("m-tag")){let s=c.replace(/\n/g,"").replace(/\s+/g," "),p=/option="(.*?)"/g,o=/ticker="(.*?)"/g,a=/currency="(.*?)"/g,i=p.exec(s),h=o.exec(s);u=a.exec(s);let f=yield g(i,h);e=e.replace(c,f)}t.innerHTML=e}))});function g(t,e){return l(this,null,function*(){switch(t[1]){case"analysis":return`<a href="${r}">${tag[1].toUpperCase()}</a>`;case"term":return`<a href="${r}">${tag[1].toUpperCase()}</a>`;case"search":let r="https://www.mexem.com/search?query="+tag[1];return`<a href="${r}">${tag[1].toUpperCase()}</a>`;case"price":let n=u[1],c=yield m(e[1]);return w(c,n);default:break}})}function m(t){return l(this,null,function*(){try{let e=yield fetch(`https://financialmodelingprep.com/api/v3/quote/${t}?apikey=814ec78e2473ac4c01ac84f650c9ce22`);if(!e.ok)throw new Error(`HTTP error! Status: ${e.status}`);return(yield e.json())[0]}catch(e){throw console.error("There was a problem with the fetch operation:",e.message),e}})}function w(t,e){let r=t.change[0]==="-"?"down":"up",n=y(t.price,e);return`<span style="display:inline-flex; align-items:center; justify-content:space-between;">
          (
          <span class="exchange-ticker" style="margin:0 8px;"> ${t.exchange}:${t.symbol} </span>
          <span  class="inline-blog-ticker-price ${r}"> ${n} </span>
          <svg  fill="currentColor" class="inline-blog-ticker-caret ${r} pulsate" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="display: block;">
            <path d="M6.1018 16.9814C5.02785 16.9814 4.45387 15.7165 5.16108 14.9083L10.6829 8.59762C11.3801 7.80079 12.6197 7.80079 13.3169 8.59762L18.8388 14.9083C19.5459 15.7165 18.972 16.9814 17.898 16.9814H6.1018Z"></path>
          </svg>
          )
        </span>`}function y(t,e){return formatCurr=e||"USD",new Intl.NumberFormat("en-US",{style:"currency",currency:formatCurr}).format(t)}})();
